urbanizze/map/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from .views import home, create, list
from urbanizze.research.views import research
from .views import geojson_zonas, geojson_setor
from .views import reverse_geocoding, export, result

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^pesquisa/$', research, name='research'),
    url(r'^cadastro/$', create, name='cadastro'),
    url(r'^terrenos/$', list, name='terrenos'),
    url(r'^zonas.geojson/$', geojson_zonas, name='geojson_zonas'),
    url(r'^setor.geojson/$', geojson_setor, name='geojson_setor'),
    url(r'^ajax/geocoding/$', reverse_geocoding, name='reverse_geocoding'),
    url(r'^(?P<pk>\d+)/export/$', export, name='export'),
    url(r'^resultado/(\d+)/$', result, name='result'),
]

urbanizze/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('urbanizze.map.urls', namespace='home')),
    url(r'^accounts/', include('urbanizze.accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

urbanizze/map/models.py
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.core.exceptions import ValidationError


EDIFICATION = (
    ('Comercial', 'Comercial'),
    ('Residencial', 'Residencial'),
    ('Industrial', 'Industrial'),
    ('Institucional', 'Institucional'),
)


class Setor(models.Model):
    nome = models.CharField('nome', max_length=50)
    geom = models.PolygonField(srid=4326)

    def __str__(self):
        return self.nome


class Zona(models.Model):
    nome = models.CharField('nome', max_length=50)
    geom = models.PolygonField(srid=4326)
    extenso = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Terreno(models.Model):
    descricao = models.CharField('descrição do terreno', max_length=100)
    geom = models.PolygonField(srid=4326)
    zona = models.CharField('zona', max_length=50)
    setor = models.CharField('setor', max_length=50)
    number_pav = models.IntegerField('número de pavimentações')
    edification_type = models.CharField('tipo de edificação', max_length=50,
                                        choices=EDIFICATION)
    account = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.descricao

    def terreno_many_zones_issue(self):
        errors = {}
        if not self.number_pav:
            msg = 'É necessário informar a quantidade de pavimentos do seu terreno.'
            errors.setdefault('geom', []).append(msg)
        if not self.descricao:
            msg = 'É necessário identificar o seu terreno com uma descrição.'
            errors.setdefault('geom', []).append(msg)
        try:
            Zona.objects.get(geom__contains=self.geom)
            Setor.objects.get(geom__contains=self.geom)
        except:
            if self.geom:
                msg1 = '''
                O polígono do terreno que você desenhou está contido em mais de uma zona urbana.
                '''
                msg2 = '''
                Refaça o desenho de forma que o terreno fique contido somente em uma zona.
                '''
                msg3 = '''
                Para auxiliar essa ação ative a camada de visualização das zonas urbanas no mapa de consultas.
                '''
                errors.setdefault('geom', []).append(msg1)
                errors.setdefault('geom', []).append(msg2)
                errors.setdefault('geom', []).append(msg3)
        if errors:
            raise ValidationError(errors)

    def clean(self):
        self.terreno_many_zones_issue()

    def save(self, *args, **kwargs):
        self.zona = Zona.objects.get(geom__contains=self.geom)
        self.setor = Setor.objects.get(geom__contains=self.geom)
        super(Terreno, self).save(*args, **kwargs)


class CodUrbanismo(models.Model):
    zona = models.CharField(max_length=50)
    uso_permitido = models.CharField(max_length=50)
    area_minima = models.CharField(max_length=50)
    frente_minima = models.CharField(max_length=50)
    taxa_ocupacao = models.CharField(max_length=50)
    altura_maxima = models.CharField(max_length=50)
    afast_frente = models.CharField(max_length=50)
    afast_lateral = models.CharField(max_length=50)
    afast_fundos = models.CharField(max_length=50)

urbanizze/research/models.py
from django.contrib.auth.models import User
from django.db import models


class Research(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

urbanizze/map/forms.py
from django import forms
from urbanizze.map.models import Terreno

EDIFICATION = (
    ('Comercial', 'Comercial'),
    ('Residencial', 'Residencial'),
    ('Industrial', 'Industrial'),
    ('Institucional', 'Institucional'),
)


class TerrenoForm(forms.ModelForm):
    label_edification = '3. Qual o tipo de edificação você deseja construir?'
    label_pav = '4. Quantos pavimentos teria sua edificação?'
    label_address = 'Localize'
    label_desc = 'Identifique'

    edification_type = forms.ChoiceField(label=label_edification,
                                         choices=EDIFICATION, required=True)
    number_pav = forms.IntegerField(label=label_pav,min_value=1,
                                    required=False)
    address = forms.CharField(label=label_address, required=False)
    descricao = forms.CharField(label=label_desc)

    class Meta:
        model = Terreno
        fields = ('edification_type', 'number_pav',
                  'address', 'descricao', 'geom',
                  'account')
        widgets = {'geom': forms.HiddenInput(), 'account': forms.HiddenInput()}

urbanizze/map/views.py
import json

from decouple import config

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.gis.geos import GEOSGeometry
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from djgeojson.views import GeoJSONLayerView

from geopy.geocoders import GoogleV3

from urbanizze.map.forms import TerrenoForm
from urbanizze.map.models import Terreno, Zona, Setor, CodUrbanismo


class ZonasGeoJson(GeoJSONLayerView):
    model = Zona
    properties = ('nome',)


class SetorGeoJson(GeoJSONLayerView):
    model = Setor
    properties = ('nome',)


geojson_zonas = ZonasGeoJson.as_view()
geojson_setor = SetorGeoJson.as_view()


def home(request):
    return render(request, 'index.html')


@login_required()
def list(request):
    terrenos = Terreno.objects.all()
    users = User.objects.all()

    for terreno in terrenos:
        for user in users:
            if terreno.account_id == user.id:
                terreno.username = user.username

    return render(request, 'list.html', {'terrenos': terrenos})


@login_required()
def create(request):
    form = TerrenoForm(request.POST or None, initial={'account': request.user})

    if form.is_valid():
        terreno = form.save()
        return redirect('home:result', terreno.pk)

    context = {
        'form': form,
        'x': settings.MAP_CENTER_X,
        'y': settings.MAP_CENTER_Y,
        'zoom_init': settings.ZOOM_INIT,
    }

    return render(request, 'create.html', context)


# TODO ~ extract this method
def result(request, pk):
    try:
        terreno = Terreno.objects.get(pk=pk)
    except Terreno.DoesNotExist:
        raise Http404

    cod_result = CodUrbanismo.objects.filter(zona=terreno.zona)
    # obj_zona = Zona.objects.get(nome=terreno.zona)
    obj_zona = Zona.objects.get(geom__contains=terreno.geom)

    if len(cod_result) == 0:
        return render(request, 'no_data.html')

    zona = terreno.zona
    zona_extenso = obj_zona.extenso
    cidade = 'João Pessoa'
    tipo_edificacao = terreno.edification_type
    numero_pavimento = terreno.number_pav
    uso_permitido = [x.uso_permitido for x in cod_result]

    if tipo_edificacao == 'Comercial':
        uso_permitido = [x for x in uso_permitido if 'Comércio' in x]
    else:
        uso_permitido = [x for x in uso_permitido if tipo_edificacao in x]

    numero_uso_permitido = len(uso_permitido)
    numero_pavimento_permitido = True

    if zona == 'ZR-1':
        if tipo_edificacao != 'Residencial':
            return render(request, 'no_data.html')
    elif zona == 'ZT-2':
        if tipo_edificacao != 'Comercial':
            return render(request, 'no_data.html')
    elif zona == 'ZA-3':
        if tipo_edificacao == 'Industrial' or tipo_edificacao == 'Institucional':
            return render(request, 'no_data.html')

    if zona == 'ZR-1' or zona == 'ZT-2':
        if numero_pavimento > 4:
            return render(request, 'no_data.html')
    elif zona == 'ZA-3':
        if numero_pavimento >= 3 and tipo_edificacao == 'Residencial':
            numero_pavimento_permitido = False

    context = {
        'terreno': terreno,
        'zona': zona,
        'zona_extenso': zona_extenso,
        'cidade': cidade,
        'tipo_edificacao': tipo_edificacao,
        'numero_pavimento': numero_pavimento,
        'uso_permitido': uso_permitido,
        'numero_uso_permitido': numero_uso_permitido,
        'cod_result': cod_result,
        'numero_pavimento_permitido': numero_pavimento_permitido,
    }

    return render(request, 'result.html', context)


def reverse_geocoding(request):
    if request.is_ajax() and request.POST:
        geolocator = GoogleV3(api_key=config('GOOGLE_MAPS_API_KEY'))
        address = request.POST.get('address')
        try:
            location = geolocator.geocode("{}".format(address))

            geodata = {'address': location.address,
                       'latitude': location.latitude,
                       'longitude': location.longitude}

            return HttpResponse(json.dumps(geodata),
                                content_type='application/json')
        except:
            raise Http404
    else:
        raise Http404


@login_required()
def export(request, pk):
    import os

    _id = pk
    path = settings.MEDIA_ROOT + '/'
    host = "-h localhost -u urbanizze -P {} {}"
    host = host.format(config('DATABASE_PASSWORD'),
                       config('DATABASE_USERNAME'))
    sql = 'SELECT geom FROM map_terreno WHERE id = {}'.format(_id)

    # create shape file
    os.system('pgsql2shp -f {}terreno_{} {} "{}"'
              .format(path, _id, host, sql))

    # create dxf file
    os.system('ogr2ogr -f DXF {0}terreno_{1}.dxf {0}terreno_{1}.shp'
              .format(path, _id))

    return render(request, 'export.html', {'pk': pk})

urbanizze/research/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url as r

from urbanizze.research.models import Research
from urbanizze.map.views import create


def research(request):
    if request.method == 'POST':
        if 'research-approved' in request.POST:
            try:
                research = Research.objects.get(user=request.user)
                research.accepted = True
                research.save()
            except:
                try:
                    if request.user:
                        res = Research(user=request.user, accepted=True)
                        res.save()
                except:
                    pass
            return HttpResponseRedirect(r('home:cadastro'))
        else:
            return HttpResponseRedirect(r('home:home'))
    else:
        try:
            research = Research.objects.get(user=request.user)
        except:
            return render(request, 'research.html')
        if not research.accepted:
            return render(request, 'research.html')
        else:
            return HttpResponseRedirect(r('home:cadastro'))

urbanizze/map/templates/aaaa.html
<!-- mapserver template -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>WEBCADASTRO</title>
<link href="[root]/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="[root]/css/main.css" rel="stylesheet">
<link rel="shortcut icon" href="[root]/img/mapserver.ico"/>
<script type="text/javascript" src="[root]/js/main.js"></script>
<link rel="stylesheet" type="text/css" href="[root]/css/main.css">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
aria-expanded="false" aria-controls="navbar">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">Mapserver Bootstrap</a>
</div>
<div id="navbar" class="collapse navbar-collapse">
<ul class="nav navbar-nav">
<li class="active"><a href="#">Início</a></li>
<li><a href="#">Mapa</a></li>
<li><a href="#about">Sobre</a></li>
<li><a href="#contact">Contato</a></li>
</ul>
</div><!--/.nav-collapse -->
</div>
</nav>

<div class="container">

<div class="row">

<div class="col-md-12">
<a href="javascript:zoomExtend();" title="Zoom Extendido">
<img src="[root]/etc/botoes/extent.png"/>
</a>
<a href="javascript:zoomIn();" title="Aproximar">
<img src="[root]/etc/botoes/in.png"/>
</a>
<a href="javascript:zoomOut();" title="Afastar">
<img src="[root]/etc/botoes/out.png"/>
</a>
<a href="javascript:pan();" title="Mover">
<img src="[root]/etc/botoes/pan.png"/>
</a>
<a href="javascript:query();" title="Consultar">
<img src="[root]/etc/botoes/attributes.png"/>
</a>
</div>


<div class="col-md-9">
<form name="form" action="[program]" method="get">
<input name="img" type="image" src="[img]" class="img-thumbnail"/>

<p>
<img alt="escala" src="[scalebar]" class="img-thumbnail"/>
</p>

</div>

<div class="col-md-3">

<img alt="mapa de referência" src="[ref]"/>

<br/>

<hr/>

<h3>Camadas:</h3>

<p><input type="checkbox" name="layer" value="logradouros" onclick="javascript:reload();"
[logradouros_check]/>Ruas e Avenidas</p>
<p><input type="checkbox" name="layer" value="lotes" onclick="javascript:reload();" [lotes_check]/>Lotes</p>
<p><input type="checkbox" name="layer" value="postes" onclick="javascript:reload();" [postes_check]/>Postes
</p>
<p><input type="checkbox" name="layer" value="bairros" onclick="javascript:reload();" [bairros_check]/>Bairros
</p>
<p><input type="checkbox" name="layer" value="quick_bird" onclick="javascript:reload();"
[quick_bird_check]/>Imagem de Satélite</p>

<br/>

<hr/>

<h3>Legenda:</h3>

<img alt="legenda" src="[legend]"/>


</div>

<input name="program" type="hidden" value="[program]"/>

<input name="map" type="hidden" value="[map]"/>

<input name="imgext" type="hidden" value="[mapext]"/>

<input name="imgxy" type="hidden" value="[center]"/>

<input name="zoomsize" type="hidden" value="2"/>

<input name="mapext" type="hidden" value="shapes"/>

<input name="root" type="hidden" value="[root]"/>

<input name="mode" value="browse" type="hidden"/>

<input name="zoomdir" value="0" type="hidden"/>

<input name="mapwidth" value="[mapwidth]" type="hidden"/>

<input name="mapheight" value="[mapheight]" type="hidden"/>

</form>


</div><!-- row -->
</div><!-- container -->


</body>
</html>

urbanizze/map/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Urbanizze{% endblock %}</title>
    <link href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% block extra_assets %}
    {% endblock extra_assets %}

</head>

<body>

{% include 'partials/navbar.html' %}

<div class="container">

    {% block content %}
    {% endblock content %}

</div>

{% block footer %}
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock footer %}

</body>
</html>

urbanizze/map/templates/export.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="row">

        <div class="col-md-12">

			<h1>Análise do Potencial construtivo</h1>
			<hr>

			<ul>
				<li>1. Assista o tutorial abaixo para compreender como utilizá-lo.</li>
				<br>
				<video width="900" height="535" controls>
					<source src="{{ MEDIA_URL }}docs/grupoBIM/prototipo-tutorial.mp4" type="video/mp4">
				</video>
				<br>
				<br>
				<li>2. Realize o levantamento Topográfico com um profisional.</li>
				<li><a rel="nofollow" href="{{ MEDIA_URL }}docs/grupoBIM.rar" download>3. Clique aqui para baixar o arquivo template do Revit.</a></li>
            </ul>
						<!-- <a rel="nofollow" href="{{ MEDIA_URL }}terreno_{{ pk }}.dxf" download>Clique aqui para baixar o arquivo DXF</a> -->
				<!-- <br> -->
        </div><!-- col-md-12 -->



	</div><!-- row -->

{% endblock content %}


{% block footer %}
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock footer %}

urbanizze/map/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="row">

        <div class="col-md-12">
            <div class="jumbotron">
                <h1>Urbanizze</h1>
                <p>Visualize. Entenda. Decida.</p>
                <p>
                    <a class="btn btn-primary btn-lg" href="{% url 'home:research' %}" role="button">
                        Começe agora mesmo &raquo;
                    </a>
                </p>
            </div>
        </div><!-- col-md-12 -->
    </div><!-- row -->

{% endblock content %}


{% block footer %}
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock footer %}

urbanizze/map/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="row">

        <div class="col-md-12">

			<h1>Relação dos terrenos</h1>
            <hr>

			<h4></h4>
			<h5>Para visualizar os detalhes do terreno acessar o link através da descrição do terreno consultado.</h5>
			<h1></h1>
			<br>

            <ul>
                {% for terreno in terrenos %}
                {% if terreno.account_id == user.id or user.is_superuser %}
                <li>
					Descrição do Terreno: <a href="{% url 'home:result' terreno.pk %}">{{ terreno.descricao }}</a><br>
                    Zona: {{ terreno.zona }}
					{% if user.is_superuser %}
					<p/>
					Usuário: {{ terreno.username }}
					{% endif %}
                </li>
				<br>
                {% endif %}
                {% endfor %}
            </ul>

        </div><!-- col-md-12 -->

    </div><!-- row -->

{% endblock content %}


{% block footer %}
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock footer %}

urbanizze/map/templates/no_data.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="error-template">
		<h2>Lamentamos...</h2>
		<div class="error-details">
		...mas nosso banco de dados ainda não tem informações suficientes para responder essa questão.
		</div>
		<br>
		<p>
			<a class="btn btn-primary btn-lg" href="{% url 'home:cadastro' %}" role="button" style="font-size: small">
				CADASTRAR NOVO TERRENO
			</a>
			<a class="btn btn-primary btn-lg" href="{% url 'home:terrenos' %}" role="button" style="font-size: small">
				VISUALIZAR LISTA DE TERRENOS
			</a>
		</p>
</div>

{% endblock content %}

urbanizze/map/templates/research.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="row">

        <div class="col-md-12">
            <div class="jumbotron">
                <h1>Urbanizze</h1>
                <p></p>
                <p>Esse website é parte de um pesquisa científica em desenvolvimento no laboratório de
                   Modelagem e Prototipagem – LM+P vinculado ao programa de Pós-graduação
                   de Arquitetura e Urbanismo da Universidade Federal da Paraíba.</p>
                <p><strong>Você tem interesse em participar como voluntário para conhecer os
                  resultados de sua aplicação?</strong></p>
                <p></p>
				<form action="#" method="post">
                {% csrf_token %}
                <p>
                    <input type="submit" value="SIM" class="btn btn-primary btn-lg" role="button" style="font-size: small" name="research-approved"\>
                    <input type="submit" value="NÃO" class="btn btn-primary btn-lg" role="button" style="font-size: small" name="research-denied"\>
                </p>
				</form>
            </div>
        </div><!-- col-md-12 -->
    </div><!-- row -->

{% endblock content %}


{% block footer %}
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock footer %}

urbanizze/map/templates/result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="row">

        <div class="col-md-12">

           <h1>Resultados</h1>
            <hr>

			<h4>Seu terreno se localiza na zona urbana {{ zona }} ({{ zona_extenso }}) da cidade de {{ cidade }}.</h4>

			<p>De acordo com o mapa de macrozoneamento dessa cidade seu terreno está numa Zona Adensável Prioritária (ZAP)
			onde é permitido construir até 4 (quatro) vezes a area do seu terreno.</p>

			<h3>Quanto ao tipo de edificação que você deseja construir:</h3>

			{% if numero_uso_permitido == 1 %}
			<p>Sim, é permitido atividade {{ tipo_edificacao }} com {{ numero_pavimento }} pavimento(s) nessa área da cidade em uma única forma de uso:</p>
			{% elif numero_uso_permitido > 1 %}
			<p>Sim, é permitido atividade {{ tipo_edificacao }} com {{ numero_pavimento }} pavimento(s) nessa área da cidade em {{ numero_uso_permitido }} diferentes usos.
			São eles:</p>
			{% else %}
			<p>Não é permitido atividade {{ tipo_edificacao }}. Sendo permitido {{ numero_uso_permitido }} diferentes usos. São eles:</p>
			{% endif %}

			{% for uso in uso_permitido %}
            <ul>
				<li>{{ uso }}</li>
            </ul>
			{% endfor %}

			<br>

			<table class="table table-reflow table-bordered">
			<thead>
				<tr>
					<th colspan="1" scope="colgroup">USOS</th>
					<th colspan="2" scope="colgroup">LOTE</th>
					<th colspan="5" scope="colgroup">EDIFICAÇÃO</th>
				</tr>

				<tr>
				<th>Permitido</th>
				<th>Área mínima</th>
				<th>Frente mínima</th>
				<th>Taxa de ocupação máxima (%)</th>
				<th>Altura máxima</th>
				<th>Afastamento frente</th>
				<th>Afastamento lateral</th>
				<th>Afastamento fundos</th>
				</tr>
			</thead>
			{% for cod in cod_result %}
			{% if cod.uso_permitido in uso_permitido %}
			<tbody>
				<td>{{ cod.uso_permitido }}</th>
				<td>{{ cod.area_minima }}</td>
				<td>{{ cod.frente_minima }}</td>
				<td>{{ cod.taxa_ocupacao }}</td>
				<td>{{ cod.altura_maxima }}</td>
				<td>{{ cod.afast_frente }}</td>
				<td>{{ cod.afast_lateral }}</td>
				<td>{{ cod.afast_fundos }}</td>
				</tr>
			</tbody>
			{% endif %}
			{% endfor %}
			</table>

			<br>

			<h3>Entenda o que significa cada parâmetro das zonas urbanas de {{ cidade }}.</h3>
			<h4>Do Lote Urbano</h4>
			<h5>Área Mínima:</h5>
			<p>Corresponde ao valor mínimo a ser considerado para a área do seu lote para o uso permitido que se deseja construir.</p>
			<h5>Frente Mínima:</h5>
			<p>Corresponde ao valor mínimo a ser considerado dimensão linear do muro frontal ou testada do terreno para o uso permitido que se deseja construir.</p>

			<br>
			<h4>Da Edificação</h4>
			<h5>Taxa de Ocupação Máxima:</h5>
			<p>Essa taxa é o valor correspondente ao valor máximo que a projeção da área do perímetro da edificação pode ter sobre a área do terreno.</p>
			<h5>Indice de aproveitamento:</h5>
			<p>Esse número corresponde um valor que multiplicado pela área do terreno informará quantidade máxima permitida para a área construída da edificação.</p>
			<h5>Altura Máxima:</h5>
			<p>Esse valor corresponde ao número máxima de pavimentos que a edificação poderá obter.</p>
			<h5>Afastamentos de frente, lateral e fundos:</h5>
			<p>Esses valores correspondem às distâncias mínimas que a edificação deve ter dessas divisas do terreno.</p>

			<br>
			<h3>Em relação a quantidade de pavimentos da sua edificação:</h3>

			{% if numero_uso_permitido == 1 %}
			<p>Sim, é possível ter {{ numero_pavimento }} pavimento(s) para um único tipo de uso {{ terreno.edification_type }} permitido na {{ zona_extenso }} ({{ zona }}).</p>
			{% elif numero_uso_permitido > 1 %}
			<p>Sim, é possível ter {{ numero_pavimento }} pavimento(s) para qualquer um dos tipos de uso {{ terreno.edification_type }} permitido na {{ zona_extenso }} ({{ zona }}).</p>
			{% else %}
			<p>Não é permitido ter {{ numero_pavimento }} pavimento(s) para os tipos de uso {{ terreno.edification_type }} na {{ zona_extenso }} ({{ zona }}).</p>
			{% endif %}

			<br>
			<h4>Gostaria de visualizar o potencial construtivo do seu terreno utilizando esses parâmetros da {{ zona_extenso }}?</h4>
			<p>
				<a class="btn btn-primary btn-lg" href="{% url 'home:export' terreno.pk %}" role="button" style="font-size: small">
					SIM
				</a>
				<a class="btn btn-primary btn-lg" href="{% url 'home:cadastro' %}" role="button" style="font-size: small">
					NÃO
				</a>
			</p>
			<br>

			<h5>Todas as informações aqui apresentadas foram extraídas do Código de Urbanismo da cidade de João Pessoa. Caso deseje consultar na íntegra o documento disponível no site da prefeitura
			<a href="http://www.joaopessoa.pb.gov.br/portal/wp-content/uploads/2012/03/codi_urba.pdf?x92016">clique aqui.</a></h5>

			<br>
			<br>

        </div><!-- col-md-12 -->

    </div><!-- row -->

{% endblock content %}


{% block footer %}
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock footer %}